### PR TITLE
Add schema version 0.0 and fix validation/upgrade commands

### PR DESCRIPTION
**Pull request by jwindhager**

### CODE REVIEW

**Comment by cavenel** [comment]
Here are some useful things related:
 - The javascript code converting version 0.0 files to version 0.1: https://github.com/TissUUmaps/TissUUmaps/blob/fdb90a0a03e87cdec7dc176e95aeb16b7152bc80/tissuumaps/static/js/utils/projectUtils.js#L512
 - An example of tmap file version 0.0 (in .txt as GitHub doesn't support .tmap files): [project_v00.txt](https://github.com/TissUUmaps/TissUUmaps-schema/files/12393705/project_v00.txt)
 - The same file saved in v0.1: [project_v01.txt](https://github.com/TissUUmaps/TissUUmaps-schema/files/12393710/project_v01.txt)

**Comment by jwindhager** [comment]
I've now changed ExpectedHeader to ExpectedCSV. Could you maybe review the changes and address the remaining TODOs in `tissuumaps_schema.v00.project` @cavenel?

Also, a couple of questions:
1. Does [this](https://github.com/TissUUmaps/TissUUmaps/blob/fdb90a0a03e87cdec7dc176e95aeb16b7152bc80/tissuumaps/static/js/utils/projectUtils.js#L541-L542) imply that v0.1 should have `uid="uniquetab"` as default?
2. Is [this](https://github.com/TissUUmaps/TissUUmaps/blob/fdb90a0a03e87cdec7dc176e95aeb16b7152bc80/tissuumaps/static/js/utils/projectUtils.js#L550-L551) commented out on purpose?
3. Anything missing [here](https://github.com/TissUUmaps/TissUUmaps/blob/fdb90a0a03e87cdec7dc176e95aeb16b7152bc80/tissuumaps/static/js/utils/projectUtils.js#L553C23-L554)?

**Comment by cavenel** [comment]
> 1. Does [this](https://github.com/TissUUmaps/TissUUmaps/blob/fdb90a0a03e87cdec7dc176e95aeb16b7152bc80/tissuumaps/static/js/utils/projectUtils.js#L541-L542) imply that v0.1 should have `uid="uniquetab"` as default?

Not sure. Making `uid="uniquetab"` default means all buttons open in the same tab, replacing each other. This is the intended behavior for tmap files version 0.0 as TissUUmaps didn't support multiple tabs back then. But it shouldn't be the default for later versions I believe.
Putting default to `null` will create a random uid on the first button click, and will open each markerFile in a different tab, which is a good default behavior.

> 2. Is [this](https://github.com/TissUUmaps/TissUUmaps/blob/fdb90a0a03e87cdec7dc176e95aeb16b7152bc80/tissuumaps/static/js/utils/projectUtils.js#L550-L551) commented out on purpose?

I think it can safely be ignored/removed. The number of projects using `glUtils._globalMarkerScale` setting must be pretty small, and it was giving strange behavior on some datasets.

> 3. Anything missing [here](https://github.com/TissUUmaps/TissUUmaps/blob/fdb90a0a03e87cdec7dc176e95aeb16b7152bc80/tissuumaps/static/js/utils/projectUtils.js#L553C23-L554)?

Common sense is missing here. Just remove the whole thing :-D

**Comment by jwindhager** [comment]
@cavenel I've now set the default of v0.0 to `uid="uniquetab"` and implemented the upgrade path. There are still some `FIXME` and `TODO` comments in `tissuumaps_schema.v00.Project` and `tissuumaps_schema.v01.Project._upgrade_previous`, could you maybe take a look when you have time? :innocent:

**Pull request merged**
